spring:
  application:
    name: Probe
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GH_CLIENT_ID}
            client-secret: ${GH_CLIENT_SECRET}
            scope:
              - read:user
              - user:email
              - repo
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000
          connectiontimeout: 5000
          writetimeout: 5000

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-minutes: 30
  refresh-token-expiration-days: 7

oauth2:
  frontend-redirect-url: ${FRONTEND_REDIRECT_URL}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

app:
  server:
    url: ${SERVER_URL}

# AI 서버 스펙 나오면 수정
# ai-server:
  # url: ${AI_SERVER_URL}
  # api-key: ${AI_SERVER_API_KEY:}
  # timeout:
    # connect: 5000
    # read: 300000
